# Generated by Django 4.2.7 on 2023-11-13 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_questao_alternativa_correta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='questao',
        ),
        migrations.AddField(
            model_name='questao',
            name='questionario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.questionario'),
        ),
    ]
