# Generated by Django 4.2.7 on 2023-11-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_questionariorespondido_data_realizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='alternativa_submetida',
        ),
        migrations.AddField(
            model_name='questionariorespondido',
            name='respostas_pessoa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
