# Generated by Django 4.2.7 on 2023-11-25 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_questao_alternativa_submetida_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fisico',
            old_name='descricao',
            new_name='biografia',
        ),
    ]
