# Generated by Django 4.2.7 on 2023-11-26 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_descricao_fisico_biografia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_a',
            new_name='alternativa_A',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_b',
            new_name='alternativa_B',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_c',
            new_name='alternativa_C',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_d',
            new_name='alternativa_D',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_e',
            new_name='alternativa_E',
        ),
    ]
