# Generated by Django 4.2.7 on 2023-11-27 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_alternativa_a_questao_alternativa_a_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Área', 'verbose_name_plural': 'Áreas'},
        ),
        migrations.AlterModelOptions(
            name='fisico',
            options={'verbose_name': 'Físico', 'verbose_name_plural': 'Físicos'},
        ),
        migrations.AlterModelOptions(
            name='invencao',
            options={'verbose_name': 'Invenção', 'verbose_name_plural': 'Invenções'},
        ),
        migrations.AlterModelOptions(
            name='subarea',
            options={'verbose_name': 'Subárea', 'verbose_name_plural': 'Subáreas'},
        ),
        migrations.AlterModelOptions(
            name='topico',
            options={'verbose_name': 'Tópico', 'verbose_name_plural': 'Tópicos'},
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_A',
            new_name='alternativa_a',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_B',
            new_name='alternativa_b',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_C',
            new_name='alternativa_c',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_D',
            new_name='alternativa_d',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_E',
            new_name='alternativa_e',
        ),
        migrations.AlterField(
            model_name='area',
            name='descricao',
            field=models.CharField(max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='area',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='fisico',
            name='biografia',
            field=models.CharField(max_length=300, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='fisico',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='fisico',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='invencao',
            name='ano',
            field=models.DateField(verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='invencao',
            name='area',
            field=models.ManyToManyField(to='app.area', verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='invencao',
            name='fisico',
            field=models.ManyToManyField(to='app.fisico', verbose_name='Físico'),
        ),
        migrations.AlterField(
            model_name='invencao',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.area', verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='descricao',
            field=models.CharField(max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='topico',
            name='descricao',
            field=models.CharField(max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='topico',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='topico',
            name='subarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subarea', verbose_name='Subárea'),
        ),
    ]
