# Generated by Django 4.2.7 on 2023-11-27 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_area_options_alter_fisico_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocupacao',
            options={'verbose_name': 'Ocupação', 'verbose_name_plural': 'Ocupações'},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AlterModelOptions(
            name='questao',
            options={'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
        migrations.AlterModelOptions(
            name='questionario',
            options={'verbose_name': 'Questionário', 'verbose_name_plural': 'Questionários'},
        ),
        migrations.AlterModelOptions(
            name='questionariorespondido',
            options={'verbose_name': 'Questionário respondido', 'verbose_name_plural': 'Questionários respondidos'},
        ),
        migrations.AlterField(
            model_name='fisico',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='ocupacao',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='ocupacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ocupacao', verbose_name='Ocupação'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_a',
            field=models.CharField(max_length=300, verbose_name='Alternativa A'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_b',
            field=models.CharField(max_length=300, verbose_name='Alternativa B'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_c',
            field=models.CharField(max_length=300, verbose_name='Alternativa C'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_correta',
            field=models.CharField(max_length=1, verbose_name='Alternativa correta'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_d',
            field=models.CharField(max_length=300, verbose_name='Alternativa D'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_e',
            field=models.CharField(max_length=300, verbose_name='Alternativa E'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='enunciado',
            field=models.CharField(max_length=500, verbose_name='Enunciado'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.questionario', verbose_name='Questionário'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='titulo',
            field=models.CharField(max_length=80, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.area', verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='descricao',
            field=models.CharField(max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='titulo',
            field=models.CharField(max_length=80, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='questionariorespondido',
            name='data_realizacao',
            field=models.DateTimeField(verbose_name='Data de realização'),
        ),
        migrations.AlterField(
            model_name='questionariorespondido',
            name='numero_acertos',
            field=models.PositiveIntegerField(verbose_name='Número de acertos'),
        ),
        migrations.AlterField(
            model_name='questionariorespondido',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa'),
        ),
        migrations.AlterField(
            model_name='questionariorespondido',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.questionario', verbose_name='Questionário'),
        ),
        migrations.AlterField(
            model_name='questionariorespondido',
            name='respostas_pessoa',
            field=models.TextField(blank=True, null=True, verbose_name='Respostas da pessoa'),
        ),
    ]
